package digital.quebracho.lapacho

import android.content.Context
import android.graphics.Paint

/** Every emoji the keyboard offers; generated by `tools/gen_emoji.py`. */
private const val EMOJI_ASSET = "emoji.tsv"

class Emoji(val glyph: String, val words: String)

/** One tab of the emoji layer: its icon and what it holds, in Unicode's order. */
class EmojiGroup(val icon: String, val emojis: List<Emoji>)

/**
 * Reads the emoji list: `#group <icon>` lines open a tab, the rest are
 * `<emoji>\t<words>`. [drawable] drops what the phone cannot draw — an emoji
 * newer than its font would show up as an empty box.
 */
fun parseEmoji(text: String, drawable: (String) -> Boolean = { true }): List<EmojiGroup> {
    val groups = mutableListOf<EmojiGroup>()
    var current: MutableList<Emoji>? = null
    for (line in text.lineSequence()) {
        if (line.startsWith("#group ")) {
            current = mutableListOf()
            groups += EmojiGroup(line.removePrefix("#group ").trim(), current)
            continue
        }
        val tab = line.indexOf('\t')
        if (line.startsWith("#") || tab < 0 || current == null) continue
        val glyph = line.substring(0, tab)
        if (drawable(glyph)) current += Emoji(glyph, line.substring(tab + 1))
    }
    return groups.filter { it.emojis.isNotEmpty() }
}

/**
 * What matches [query] by name or keyword, in Spanish or English. Whole
 * words rank first, then words it starts, then anywhere inside one: "mate"
 * is 🧉 before it is the "materna" of 🤱. Then a plain emoji before a
 * combined one ("fuego" is 🔥 before ❤️‍🔥), then the one where the word
 * comes earlier: each line starts with the name, so "fuego" is 🔥 (its
 * name) before 🚒 (a keyword).
 */
fun searchEmoji(groups: List<EmojiGroup>, query: String, limit: Int): List<Emoji> {
    val terms = fold(query).split(' ').filter { it.isNotEmpty() }
    if (terms.isEmpty()) return emptyList()
    return groups.flatMap { it.emojis }.filter { matchesQuery(it.words, query) }
        .sortedWith(
            compareBy<Emoji>({ e ->
                val words = e.words.split(' ')
                // Per term: 0 for a whole word, 1 for the start of one, 2 for inside one.
                terms.count { it !in words } + terms.count { t -> words.none { it.startsWith(t) } }
            }, { it.glyph.length }, { e -> e.words.split(' ').indexOfFirst { it.startsWith(terms.first()) } }),
        )
        .take(limit)
}

/**
 * The user's favourite emoji, newest first, as stored: one line, space
 * separated — no emoji contains a space.
 */
fun parseFavorites(saved: String?): List<String> = saved.orEmpty().split(' ').filter { it.isNotEmpty() }

/** A favourite is removed if it is one, else added in front. */
fun toggleFavorite(favorites: List<String>, glyph: String): List<String> =
    if (glyph in favorites) favorites - glyph else listOf(glyph) + favorites

/**
 * ponytail: parsed on the first open of the emoji layer (~2 000 lines plus a
 * glyph check each), kept for the keyboard's lifetime.
 */
fun loadEmoji(context: Context): List<EmojiGroup> {
    val paint = Paint()
    val text = context.assets.open(EMOJI_ASSET).bufferedReader().use { it.readText() }
    return parseEmoji(text) { paint.hasGlyph(it) }
}
